# Generated by Django 2.1.3 on 2018-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0004_auto_20181215_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='users_titles',
            field=models.ManyToManyField(blank=True, related_name='users', through='searcher.TitleInProgress', to='searcher.TitleList'),
        ),
    ]
