# Generated by Django 2.1.3 on 2018-12-19 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0005_auto_20181215_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_check',
        ),
    ]
